name: "What is the size of Pr"
description: "Will give info abut the number of file change and number of line change"
inputs:
  owner:
    description: "The owner of the repository"
    required: true
  repo:
    description: "The name of the repository"
    required: true
  pr_number:
    description: "The number of the pull request"
    required: true
  upperLimit:
    description: "Number of file after which pr should throw error message"
    required: true
  token:
    description: "The token to use to access the GitHub API"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
