name: "What is the size of Pr"
description: "Will give info abut the number of file change and number of line change"
inputs:
  upperLimit:
    description: "Number of file after which pr should throw error message"
    required: true
  token:
    description: "The token to use to access the GitHub API"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
