name: PR metadata annotation

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    steps:
      - name: Annotate PR
        uses: nikhilsoni-stack/actionTest@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          upperLimit: 10
